### ISSUE TITLE
Output data

### ISSUE THREAD

**Issue by NicoBiagi** [marsja/stroopy#2]
Hi, great script, thank you for sharing it.

I noticed that in the csv that is generated, the values are separated by a semicolon instead of a coma, and maybe for this reason they are presented in one big column instead of being presented in separate columns.

**Comment by marsja** [comment]
Hey there. Sorry for the late reply. The semicolon is the separator in the output (CSV). I used this because Windows computers using Swedish will have these as a default option. You can change this in your code to use comma instead. I will update the code when I find time. Maybe I'll add this as an option (i.e., which separator the user want to use).
